name: Release

on:
  release:
    types:
    - published

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v3
    -
      name: Build
      run: ./build.sh  ${{ github.ref_name }}
    -
      name: Add to release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./out/OJDS-NX-${{ github.ref_name }}.zip
        asset_name: OJDS-NX-${{ github.ref_name }}.zip
        asset_content_type: application/zip
